version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-cache-{{ checksum "package-lock.json" }}
            - node-cache
      - run: npm run init
      - run:
          name: prettier
          command: npm run prettier
      - run:
          name: lint
          command: npm run lint
      - run:
          name: tests
          command: npm run test -- --no-cache --ci --runInBand
      - save_cache:
          key: node-cache-{{ checksum "package-lock.lock" }}
          paths:
            - node_modules
