name: Benchmark

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  turbo:
    name: Build with Turbo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Turbo
        run: yarn build:turbo

  nx:
    name: Build with Nx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Nx
        run: yarn build:nx
