name: Node.js CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'Validate with Node v${{ matrix.node-version }}'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: yarn

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            **/.eslintcache
            **/.turbo
            node_modules/.cache/turbo
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-
            
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build packages
        run: yarn build

      - name: Lint
        run: yarn check:prettier

      - name: Type check
        run: yarn type-check

      - name: Test
        run: yarn test