name: React 17

on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  react17:
    name: Test in React 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.6

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install node-gyp
        run: pnpm run global add node-gyp

      - name: Install package.json
        run: pnpm install --prefer-offline

      - name: Build CLI
        run: pnpm build:cli

      # TODO: Will nohoist help here?
      - name: Install testing tools for React 17
        run: npx ts-node tools/test/scripts/install-react17.ts

      - name: Build packages
        run: pnpm build

      - name: Run tests in React 17
        run: pnpm run lg test --react17
