name: Version

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.LEAFYGREEN_UI_MONGO_NAV_DEPLOY }}
          submodules: 'recursive'

      # The SSH Agent manages the SSH keys used in future steps for authentication.
      - name: Set Up SSH Agent
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: |
            ${{ secrets.LEAFYGREEN_UI_DEPLOY }}
            ${{ secrets.LEAFYGREEN_UI_MONGO_NAV_DEPLOY }}

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Build typescript
        run: yarn ts:build

      - name: Create Release Pull Request
        uses: changesets/action@master
        with:
          version: yarn changeset:version
          publish: yarn release
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'

      - name: Push Changeset Updates to Submodules
        run: git submodule foreach 'git checkout -B changesets && git add . && git commit -m "changeset update" && git push -f origin changesets'

      - name: Publish website with package updates
        if: steps.changesets.outputs.published == 'true'
        run: yarn publish:sites

      - name: Notify Slack chanel of new releases
        if: steps.changesets.outputs.published == 'true'
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        with:
          # channel-id: 'C01CBLPFD35'  # leafygreen-ui-releases
          channel-id: 'GGGR7AXHP' # design-systems-team
          slack-message: ":wave: Hey there! Some new LeafyGreen updates: \n${{steps.changesets.outputs.publishedPackages | jq -r 'map(.name + \"@\" + .version) | join(\"/n\")'}}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
