name: Version

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: Build packages
        run: yarn build:packages

      - name: Build typescript
        run: yarn build:ts

      - name: Build TSDoc
        run: yarn docs:tsdoc

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          publish: yarn publish:packages
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'

      - name: Dispatch to Website repo
        uses: peter-evans/repository-dispatch@v2
        continue-on-error: true
        with:
          token: ${{ secrets.DESIGN_REPO_ACCESS_TOKEN }}
          repository: mongodb/design
          event-type: release-leafygreen-ui

      - name: Notify Slack channel of new releases
        if: steps.changesets.outputs.published == 'true'
        id: slackbot
        run: yarn slackbot '${{steps.changesets.outputs.publishedPackages}}'
        env:
          SLACK_BOT_TOKEN: '${{secrets.SLACK_BOT_TOKEN}}'

      - name: Publish storybook with package updates
        if: steps.changesets.outputs.published == 'true'
        run: yarn publish:storybook
