name: Version

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Create Release Pull Request
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Checkout changeset-release/master
        uses: actions/checkout@v2
        with:
          ref: changeset-release/master

      - name: Run prettier
        run: |
          yarn
          yarn format
          git status

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Automated publish with prettier" || exit 0
          git pull --rebase publisher @changeset-release/master
          git push publisher @changeset-release/master
