name: Version

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Build typescript
        run: yarn ts:build

      - name: Create Release Pull Request
        uses: changesets/action@master
        with:
          version: yarn changeset:version
          publish: yarn release
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'

      - name: Push Changeset Updates to Submodules
        run: git submodule foreach 'git checkout -B changesets && git add . && git commit -m "changeset update" && git push -f origin changesets'

      - name: Publish website with package updates
        if: steps.changesets.outputs.published == 'true'
        run: yarn publish:sites

      - name: Notify Slack channel of new releases
        if: steps.changesets.outputs.published == 'true'
        id: slackbot
        run: yarn slackbot '${{steps.changesets.outputs.publishedPackages}}'
        env:
          SLACK_BOT_TOKEN: '${{secrets.SLACK_BOT_TOKEN}}'
