name: Version

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Create Release Pull Request
        uses: changesets/action@master
        with:
          # this expects you to have a npm script called version that runs some logic and then calls `changeset version`.
          version: yarn cg:version
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
