name: TEST

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-cache-

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: |
          yarn build:packages --diff --deps
          yarn test --diff --deps --no-cache --ci --runInBand --reporters=default --reporters=jest-junit
          yarn test --ssr --diff --deps --no-cache --ci --runInBand --reporters=default --reporters=jest-junit

      - name: Auto Format
        uses: cloudposse/github-action-auto-format@v0.12.0
        with:
          format-task: fix
          workflow-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Check Types
        run: yarn check:ts

      - name: Check Builds
        run: yarn check:builds --diff --deps

      - name: Check File Size
        uses: fatton139/pr-comment-file-size@v3.1.1
        with:
          path: 'packages/'
          token: ${{ secrets.GITHUB_TOKEN }}
